theme: jekyll-theme-minimal
title: <img src="https://rafishiddik.github.io/images/Foto.jpg" alt="Foto Profil" width="200">
description: 
- linked : https://www.linkedin.com/in/achmad-rafi-shiddik/
markdown: kramdown
kramdown:
  input: GFM
